kind: ConfigMap
apiVersion: v1
metadata:
 name: app-config-rhdh
data:
 app-config-rhdh.yaml: |
  signInPage: oauth2Proxy
  auth:
   environment: development
   providers:
    oauth2Proxy: {}
  backend:
   auth:
    keys:
     - secret: ${BACKEND_SECRET}
  permission:
    enabled: true
    rbac:
      policies-csv-file: ./rbac/rbac-policy.csv
      admin:
        users:
        - name: 'user:admin'
        - name: 'user:default/admin'
        - name: 'user:user1'
        - name: 'user:default/user1'
