kind: Secret
apiVersion: v1
metadata:
  name: rhdh
stringData:
  BACKEND_SECRET: this_should_be_an_actually_random_secret_that_is_secret_but_this_is_a_demo_so_deal_with_it_you_have_been_warned
  # generated following instructions from https://oauth2-proxy.github.io/oauth2-proxy/configuration/overview/
  COOKIE_SECRET: m831azS2fNVzUJZa2lykJg-BDsVqXZr-lql6T0bXyRs=
type: Opaque
