apiVersion: v1
kind: ServiceAccount
metadata:
  name: rhdh
  annotations:
    serviceaccounts.openshift.io/oauth-redirecturi.backstage: 'https://backstage-rhdh-with-sso-rhdh-with-sso.apps.cluster-dc5mz.dynamic.redhatworkshops.io'
