kind: ConfigMap
apiVersion: v1
metadata:
  name: rhdh-rbac-policy
data:
  rbac-policy.csv: |
    # admin role
    p, role:default/admins, catalog.location.read, read, allow
    p, role:default/admins, catalog.location.create, create, allow
    p, role:default/admins, catalog.location.delete, delete, allow
    p, role:default/admins, catalog.entity.create, create, allow   
    p, role:default/admins, catalog.entity.delete, delete, allow 
    p, role:default/admins, catalog.entity.read, read, allow 
    p, role:default/admins, catalog.entity.refresh, refresh, allow  
    p, role:default/admins, catalog-entity, read, update, delete, allow
    p, role:default/admins, scaffolder.action.execute, use, allow
    p, role:default/admins, scaffolder.template.parameter.read, read, allow
    p, role:default/admins, scaffolder.template.step.read, read, allow
    p, role:default/admins, policy-entity.read, read, allow
    p, role:default/admins, policy-entity.create, create, allow
    p, role:default/admins, policy-entity.update, update, allow
    p, role:default/admins, policy-entity.delete, delete,allow
    p, role:default/admins, kubernetes.proxy, use, allow

    this is not needed now with the new superUser setting
    g, user:default/admin, role:default/admins