kind: ConfigMap
apiVersion: v1
metadata:
  # NOTE: this follows the pattern <backstage-cr-name>-dynamic-plugins, so if you change the backstage-cr name this needs to change too (to bad not using helm)
  name: rhdh-with-openshift-auth-dynamic-plugins
data:
  dynamic-plugins.yaml: |
    includes:
      - dynamic-plugins.default.yaml
    plugins:
    - package: ./dynamic-plugins/dist/janus-idp-backstage-plugin-rbac
      disabled: false
