kind: ConfigMap
apiVersion: v1
metadata:
 name: app-config-rhdh
data:
 app-config-rhdh.yaml: |
  signInPage: oauth2Proxy
  auth:
   environment: development
   providers:
    oauth2Proxy: {}
  backend:
   auth:
    keys:
     - secret: ${BACKEND_SECRET}
  catalog:
    locations:
    - target: https://github.com/janus-idp/backstage-showcase/blob/main/catalog-entities/all.yaml
      type: url
    - target: https://github.com/janus-idp/software-templates/blob/main/showcase-templates.yaml
      type: url
    - target: https://github.com/itewk/rhdh-with-openshift-auth/blob/main/catalog-entities/users/user1.yaml
      type: url
  permission:
    enabled: true
    rbac:
      policies-csv-file: ./rbac/rbac-policy.csv
      admin:
        users:
        - name: 'user:admin'
        - name: 'user:default/admin'
        - name: 'user:user1'
        - name: 'user:default/user1'
