apiVersion: v1
kind: ConfigMap
metadata:
  name: rhdh-runtime-config
data:
  route.yaml: |-
    apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      name: # NOTE: will be dynamically replaced by operator with 'backstage-<cr-name>'
    spec:
      port:
        targetPort: http-backend
      path: /
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: reencrypt
      to:
        kind: Service
        name: # NOTE: will be dynamically replaced by operator with 'backstage-<cr-name>'
  service.yaml: |-
    apiVersion: v1
    kind: Service
    metadata:
      name: # NOTE: will be dynamically replaced by operator with 'backstage-<cr-name>'
      annotations:
        service.beta.openshift.io/serving-cert-secret-name: rhdh-tls
    spec:
      type: ClusterIP
      selector:
        rhdh.redhat.com/app: # NOTE: will be dynamically replaced by operator with 'backstage-<cr-name>'
      ports:
        - name: http-backend
          port: 80
          targetPort: oauth-proxy
  deployment.yaml: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name:  # NOTE: will be dynamically replaced by operator with 'backstage-<cr-name>'
    spec:
      replicas: 1
      selector:
        matchLabels:
          rhdh.redhat.com/app:  # NOTE: will be dynamically replaced by operator with 'backstage-<cr-name>'
      template:
        metadata:
          labels:
            rhdh.redhat.com/app:  # NOTE: will be dynamically replaced by operator with 'backstage-<cr-name>'
        spec:
          automountServiceAccountToken: true
          serviceAccount: rhdh
          volumes:
            - ephemeral:
                volumeClaimTemplate:
                  spec:
                    accessModes:
                      - ReadWriteOnce
                    resources:
                      requests:
                        storage: 2Gi
              name: dynamic-plugins-root
            - name: dynamic-plugins-npmrc
              secret:
                defaultMode: 420
                optional: true
                secretName: dynamic-plugins-npmrc
            - name: rhdh-tls
              secret:
                defaultMode: 420
                secretName: rhdh-tls
            - name: rbac-policy
              configMap:
                name: rhdh-rbac-policy
                defaultMode: 420
          initContainers:
            - command:
                - ./install-dynamic-plugins.sh
                - /dynamic-plugins-root
              env:
                - name: NPM_CONFIG_USERCONFIG
                  value: /opt/app-root/src/.npmrc.dynamic-plugins
              # image will be replaced by the value of the `RELATED_IMAGE_backstage` env var, if set
              image: quay.io/janus-idp/backstage-showcase:latest
              imagePullPolicy: IfNotPresent
              name: install-dynamic-plugins
              volumeMounts:
                - mountPath: /dynamic-plugins-root
                  name: dynamic-plugins-root
                - mountPath: /opt/app-root/src/.npmrc.dynamic-plugins
                  name: dynamic-plugins-npmrc
                  readOnly: true
                  subPath: .npmrc
              workingDir: /opt/app-root/src
              resources:
                limits:
                  cpu: 1000m
                  memory: 2.5Gi
                  ephemeral-storage: 5Gi
          containers:
            - name: oauthproxy
              args:
                - -provider=openshift
                - -https-address=:8888
                - -http-address=
                - -email-domain=*
                - -upstream=http://localhost:7007
                - -tls-cert=/etc/tls/private/tls.crt
                - -tls-key=/etc/tls/private/tls.key
                - -cookie-secret="${COOKIE_SECRET}"
                - -openshift-service-account=rhdh
                - -openshift-ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
                - -skip-auth-regex=^/metrics
                - -skip-provider-button
                - -request-logging=true
              image: registry.redhat.io/openshift4/ose-oauth-proxy-rhel9:v4.15
              imagePullPolicy: IfNotPresent
              ports:
                - name: oauth-proxy
                  containerPort: 8888
                  protocol: TCP
              volumeMounts:
                - mountPath: /etc/tls/private
                  name: rhdh-tls
            - name: backstage-backend
              # image will be replaced by the value of the `RELATED_IMAGE_backstage` env var, if set
              image: quay.io/janus-idp/backstage-showcase:next
              imagePullPolicy: IfNotPresent
              args:
                - "--config"
                - "dynamic-plugins-root/app-config.dynamic-plugins.yaml"
              readinessProbe:
                failureThreshold: 3
                httpGet:
                  path: /healthcheck
                  port: 7007
                  scheme: HTTP
                initialDelaySeconds: 30
                periodSeconds: 10
                successThreshold: 2
                timeoutSeconds: 2
              livenessProbe:
                failureThreshold: 3
                httpGet:
                  path: /healthcheck
                  port: 7007
                  scheme: HTTP
                initialDelaySeconds: 60
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 2
              ports:
                - name: backend
                  containerPort: 7007
              env:
                - name: APP_CONFIG_backend_listen_port
                  value: "7007"
              envFrom:
                - secretRef:
                    name: <POSTGRESQL_SECRET>  # NOTE: will be replaced by operator with 'backstage-psql-secrets-<cr-name>'
              #            - secretRef:
              #                name: backstage-secrets
              volumeMounts:
                - mountPath: /opt/app-root/src/dynamic-plugins-root
                  name: dynamic-plugins-root
                - name: rbac-policy
                  mountPath: opt/app-root/src/rbac
              resources:
                limits:
                  cpu: 1000m
                  memory: 2.5Gi
                  ephemeral-storage: 5Gi