---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rhdh-with-openshift-auth

resources:
- Namespace.yaml
- ServiceAccount_rhdh.yaml
- Secret_rhdh.yaml
- ConfigMap_app-config-rhdh.yaml
- ConfigMap_rhdh-runtime-config.yaml
- ConfigMap_rhdh-rbac-policy.yaml
- ConfigMap_dynamic-plugins.yaml
- Backstage.yaml

patchesJSON6902:
- target:
    kind: ServiceAccount
    name: rhdh
  patch: |-
    - op: replace
      path: "/metadata/annotations/serviceaccounts.openshift.io~1oauth-redirecturi.backstage"
      value: "https://backstage-rhdh-with-openshift-auth-rhdh-with-openshift-auth.apps.h28yrboo.eastasia.aroapp.io"
#     https://backstage-developer-hub-rhdh-operator.apps.h28yrboo.eastasia.aroapp.io/
#     value: "https://backstage-rhdh-with-openshift-auth-rhdh-with-openshift-auth.apps.cluster-4z5xw.dynamic.redhatworkshops.io"
